### PR TITLE
(maint) move to harness.drone.io

### PR DESCRIPTION
**Pull request by tphoney**

### CODE REVIEW

**Comment by sbstp** [comment]
@tphoney this PR broke a couple of pipelines over at @rancher, we depend on the `arm` variant of the `drone/git` image to build our own `arm` images. Now our `arm` pipelines fail to pull the `drone/git` image.

Is it possible to reintroduce the `arm` variant in the manifest?

**Comment by jimsheldon** [comment]
As a temporary workaround, you should be able to pass the previous image with the linux-arm tag to your runner(s) like so:

`DRONE_RUNNER_CLONE_IMAGE=drone/git:linux-arm`

Let me know if this won't work for you.

**Comment by snasovich** [comment]
@jimsheldon , thank you. Is there a plan to re-introduce `arm` image back into `latest`? Trying to judge how "temporary" is that.

**Comment by brandond** [comment]
Yeah, we need this back ASAP. This has broken k3s-io as well.

**Comment by jimsheldon** [comment]
Can folks in this thread please share why the recommended workaround is not possible?

Our hosting provider dropped support for `linux/arm` hardware, which is why we had to remove it. To bring back support for `linux/arm`, we would need to significantly change the current pipeline to cross-compile images (likely using buildx).

> As a temporary workaround, you should be able to pass the previous image with the linux-arm tag to your runner(s) like so:
> 
> `DRONE_RUNNER_CLONE_IMAGE=drone/git:linux-arm`
> 
> Let me know if this won't work for you.

**Pull request merged**
