### PR TITLE
Add `retries` option

### PR DESCRIPTION
**Pull request by julienduchesne**
It uses the `PLUGIN_VAR` format in order to allow enabling it this way:
```
clone:
  retries: 3
```

Updated from https://github.com/drone/drone-git/pull/27

### CODE REVIEW

**Review by tphoney — APPROVED** [review]

**Comment by tphoney** [comment]
Hi @julienduchesne this seems sensible, how where you going to pass the env var in from the runners ?

**Comment by julienduchesne** [comment]
> Hi @julienduchesne this seems sensible, how where you going to pass the env var in from the runners ?

I'd like to add a `retries` attribute in the `clone` structure if possible. And pass it like this: https://github.com/drone-runners/drone-runner-docker/blob/d926749258923b7ecba054d76e51ad9b2cd6e434/engine/compiler/clone.go#L32-L42

Currently, we are using this as a custom clone step

**Comment by julienduchesne** [comment]
Thanks for the merge @tphoney. I also created these two PRs to expose the option:
- https://github.com/drone/runner-go/pull/22
- https://github.com/drone-runners/drone-runner-docker/pull/44

**Comment by sdarwin** [comment]
@julienduchesne what's the delay between retries? should sleep for 5 or 10 seconds right? Otherwise, all retries happen very quickly.

**Pull request merged**
