### PR TITLE
Added AWS codecommit support using access & secret keys

### PR DESCRIPTION
**Pull request by shubham149**

### CODE REVIEW

**Review by bradrydzewski — APPROVED** [review]

**Comment by tboerger** [comment]
The AWS CLI is a simple Python tool, right? And just for that we got GLIBC installed now, which is also not really supported by Alpine officially? Sounds like a really bad move, especially for such a core plugin like this one.

**Comment by shubham149** [comment]
@tboerger I was not able to find a way to install aws cli v2 using pip. Pip install is available only for aws cli v1 version. Installation guide of aws cli on linux: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html

**Comment by tboerger** [comment]
Looking at the conversation at https://github.com/aws/aws-cli/issues/4947 it sounds even more like a bad idea to install v2 CLI at all. If you really must install v2 I would welcome more something like a manual installation:

```
apk update && apk add git groff python3 python3-dev py3-pip py3-six py3-urllib3 py3-colorama build-base libffi-dev openssl-dev && \
  pip install git+git://github.com/aws/aws-cli.git#2.1.25 && \
  apk del python3-dev py3-pip build-base libffi-dev openssl-dev && \
  rm -rf /var/cache/apk/*
```

But as far as I read all of that the v1 published to PyPi or available as Alpine package should be totally fine until AWS is providing proper packaging for Alpine/Musl. Adding Glibc to an Alpine image really sucks pretty hard.

**Comment by shubham149** [comment]
@tboerger I have created a PR https://github.com/drone/drone-git/pull/37 to use pip for installing aws cli v1 version. Looks like aws codecommit git clone works with aws cli v1 as well.

**Comment by tboerger** [comment]
In case of using v1 you could also just use the alpine package for it :)

**Pull request merged**
